name: Reindex docs for GPT chat

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  reindex_docs:
    runs-on: ubuntu-latest
    env:
      HAS_COMMITS: false
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: gpt_docs

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - name: Reindex documents
        run: cd .github/scripts &&
          pip install -r requirements.txt &&
          python3 docs_fetcher.py

      - name: Commit files
        id: commit_files
        if: always()
        run: |
          git config --local user.email "millionalgos@pm.me"
          git config --local user.name "github-actions[bot]"

          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "[no-tweet] reindexed docs for gpt chat ðŸ¤–" || COMMIT_EXIT_CODE=$? || true
            if [ "$COMMIT_EXIT_CODE" == "0" ]; then
              echo "has_commits=true" >> $GITHUB_OUTPUT
            else
              echo "has_commits=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "no changes - skipping commit"
            echo "has_commits=false" >> $GITHUB_OUTPUT
          fi

      - name: Push files to gpt_docs branch
        run: |
          git push origin gpt_docs

